# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to dev bot instance

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    uses: './.github/workflows/build.yml'
    with:
      dev: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: seabot

      - name: ship it
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'seabot-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2A4CED61642B4E7FA66FA99139320C61 }}
          package: seabot.zip
