name: send it to prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: './.github/workflows/build.yml'
    with:
      dev: false

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: seabot

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bpi'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_a2eaf46bf295409e962e329c53788d4d }}
          package: seabot.zip